# 数据源配置
spring:
  datasource:
    #jdbc配置
    driver-class-name: com.mysql.cj.jdbc.Driver # 数据库驱动类名
    username: root # 数据库用户名
    password: dydy521521 # 数据库密码
    url: jdbc:mysql://localhost:3306/mytest1?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8 # 数据库连接 URL
    type: com.alibaba.druid.pool.DruidDataSource # 数据源类型
    # durid配置
    #   数据源其他配置
    initial-size: 5 # 初始化连接数
    min-idle: 5 # 最小空闲连接数
    max-active: 20 # 最大连接数
    max-wait: 60000 # 获取连接的最大等待时间
    time-between-eviction-runs-millis: 60000 # 两次扫描之间的时间间隔
    min-evictable-idle-time-millis: 300000 # 连接在池中保持空闲而不被空闲连接回收器线程删除的最小时间值
    validation-query: SELECT 1 FROM DUAL # 验证连接是否有效的 SQL
    test-while-idle: true # 是否在连接空闲时执行测试
    test-on-borrow: false # 是否在获取连接时执行测试
    test-on-return: false # 是否在归还连接时执行测试
    filters: stat,wall,log4j # 连接池的过滤器
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 连接属性
    max-evictable-idle-time-millis: 25200000
    time-between-connect-error-millis: 6000



  # Redis 配置
  redis:
    host: localhost # Redis 服务器地址
    port: 6379 # Redis 服务器端口号
    #password: 123456 # Redis 服务器密码
    timeout: 5000ms # Redis 连接超时时间
    lettuce:
      pool:
        max-active: 20 # 最大连接数
        max-idle: 10 # 最大空闲连接数
        min-idle: 5 # 最小空闲连接数
        max-wait: 5000ms # 获取连接的最大等待时间

# Spring Boot 应用程序配置
server:
  port: 9090 # 应用程序监听的端口号

    # 配置FastJson
  fastjson:
      # 日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    #时区
    time-zone:  GMT+8
      # 输出格式化
    pretty-format: true

  devtools:
    restart:
      # 设置热部署生效
      enabled: true
      # 设置重启的目录
      additional-paths: src/main/java
      # WEB-INF目录下内容发生更改不重启
      exclude: WEB-INF/*

# JPA 配置
  jpa:
    hibernate:
      ddl-auto: update # 自动创建/更新数据库表结构
    database: mysql # 数据库类型
    show-sql: true # 是否显示 SQL 语句

# Spring Boot 配置
  main:
    allow-bean-definition-overriding: true # 允许 Bean 定义覆盖

# Spring MVC 配置
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # URL 路径匹配策略

# MyBatis 配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # MyBatis 日志实现类
#mybatisplus配置
mybatis-plus:
  global-config:
    db-config:
      #配置id自增长
      id-type: auto
  configuration:
    #配置mybatisplus日志    MyBatis-Plus 日志实现类
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.mapper.xml      #xml文件的位置(resources下的mapper文件夹)

# 文件上传配置
  servlet:
    multipart:
      enabled: true # 是否启用文件上传功能
      file-size-threshold: 2KB # 文件大小阈值
      max-file-size: 200MB # 单个文件最大大小
      max-request-size: 215MB # 请求中所有文件的最大总大小

# 文件上传路径配置
files:
  upload:
    path: D:/java files/8/files # 上传文件保存的路径